# app.py (final integrated version)
import streamlit as st
import cv2
import numpy as np
import tempfile
import os
import traceback

# detectors / summary
from damage_detector import detect_damage_opencv   # your final, dent-boosted detector
from summary_generator import generate_summary     # keeps using your existing summary generator

# Lazy import for scratch detector (only when needed)
# from scratch_detector import detect_scratches

st.set_page_config(page_title="Smart Damage Detection System", layout="centered")

st.title("Smart Damage Detection System")
st.write(
    "Upload an image of a surface/object — the app will highlight potential damage "
    "and produce a short autogenerated summary. Use **General Damage** for dents/patches "
    "and **Thin Scratch Detection** for hairline scratches."
)

# Mode selector
mode = st.radio("Choose detection mode", ["General Damage", "Thin Scratch Detection"], index=0)

# Allow quick tuning of sensitivity for General mode
with st.expander("Advanced: Detection sensitivity (General mode)"):
    min_area = st.slider("Minimum contour area (pixels)", min_value=10, max_value=200, value=50, step=5,
                         help="Lower values detect smaller/longer defects; higher values reduce false positives.")
    show_debug = st.checkbox("Show intermediate debug images (slow)", value=False)
else_min_area = 50  # fallback if not set from UI

uploaded = st.file_uploader("Upload image (jpg, png)", type=["jpg", "jpeg", "png"])
col1, col2 = st.columns([1, 1])

def to_display_image(img):
    """Convert BGR -> RGB for Streamlit display, safe fallback."""
    try:
        return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    except Exception:
        return img

def run_general_detector(path, min_area_val, debug_flag):
    """Run the dent/damage detector and return annotated image, boxes, debug dict."""
    # detect_damage_opencv returns: annotated (BGR), boxes (list), debug_images (dict) when debug=True
    try:
        annotated, boxes, debug_imgs = detect_damage_opencv(path, min_area=min_area_val, debug=debug_flag)
    except TypeError:
        # older signature compatibility
        annotated, boxes = detect_damage_opencv(path, min_area=min_area_val)
        debug_imgs = {}
    return annotated, boxes, debug_imgs

def run_scratch_detector(path):
    """Run the thin-scratch detector (lazy import to avoid hard dependency)."""
    try:
        from scratch_detector import detect_scratches
    except Exception:
        raise FileNotFoundError("scratch_detector.py not found. Add scratch_detector.py to enable Thin Scratch Detection.")
    annotated, boxes = detect_scratches(path, min_length=20)
    return annotated, boxes, {}

# Determine image source (upload or local path)
img_path = None
uploaded_tfile = None

if uploaded:
    # Save uploaded file to a temporary file (so OpenCV can read it by path)
    try:
        uploaded_tfile = tempfile.NamedTemporaryFile(delete=False, suffix=".jpg")
        uploaded_tfile.write(uploaded.read())
        uploaded_tfile.flush()
        img_path = uploaded_tfile.name
        st.text(f"DEBUG: Saved temp image: {img_path}")
    except Exception as e:
        st.error("Failed to save uploaded file to a temporary file.")
        st.error(str(e))
        if uploaded_tfile is not None:
            try:
                uploaded_tfile.close()
            except:
                pass
            try:
                if os.path.exists(uploaded_tfile.name):
                    os.unlink(uploaded_tfile.name)
            except:
                pass
        raise

if img_path:
    try:
        # Choose which detector to run
        if mode == "General Damage":
            min_area_val = min_area if 'min_area' in locals() else else_min_area
            annotated, boxes, debug_imgs = run_general_detector(img_path, min_area_val, show_debug)
        else:
            # Thin Scratch Detection
            annotated, boxes, debug_imgs = run_scratch_detector(img_path)

        # Convert annotated image for display
        annotated_disp = to_display_image(annotated)

        # Left column: annotated image
        with col1:
            st.subheader("Annotated Output")
            st.image(annotated_disp, use_container_width=True)

        # Right column: detection details + summary
        with col2:
            st.subheader("Detection Details")
            st.write(f"Detected potential damage spots: **{len(boxes)}**")

            if len(boxes) > 0:
                for i, b in enumerate(boxes, 1):
                    if len(b) >= 6:
                        x, y, w, h, conf, sev = b
                        st.write(f"- Spot {i}: x={x}, y={y}, w={w}, h={h}, confidence={conf:.2f}, severity={sev}")
                    else:
                        x, y, w, h = b[:4]
                        st.write(f"- Spot {i}: x={x}, y={y}, w={w}, h={h}")

            st.markdown("---")
            st.subheader("Auto Summary")
            try:
                coords = [(x, y, w, h) for (x, y, w, h, *_) in boxes]
            except Exception:
                coords = [(x, y, w, h) for (x, y, w, h) in boxes]
            summary = generate_summary(coords)
            st.info(summary)

        # Debug images (optional)
        if show_debug and debug_imgs:
            st.markdown("---")
            st.subheader("Intermediate / Debug Images")
            items = list(debug_imgs.items())
            cols_n = min(3, max(1, len(items)))
            cols = st.columns(cols_n)
            for idx, (name, img) in enumerate(items):
                if img is None:
                    continue
                if len(img.shape) == 2:
                    disp = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
                else:
                    disp = img
                cols[idx % cols_n].subheader(name)
                cols[idx % cols_n].image(to_display_image(disp), use_container_width=True)

    except Exception as e:
        st.error("An error occurred during detection.")
        st.text(traceback.format_exc())

    finally:
        # cleanup temp file if one was created
        if uploaded and uploaded_tfile is not None:
            try:
                uploaded_tfile.close()
            except:
                pass
            try:
                if os.path.exists(uploaded_tfile.name):
                    os.unlink(uploaded_tfile.name)
            except:
                pass
else:
    st.info("Upload an image (or place sample images in `sample_images/`) to run detection.")

# Footer
st.markdown("---")
st.caption(
    "General Damage = detects dents/patches (uses damage_detector.py). "
    "Thin Scratch Detection = hairline scratches (uses scratch_detector.py). "
    "Adjust 'Minimum contour area' if you need to detect smaller/larger defects."
)
